Enable incremental builds for node{6,8,10} (#201)
* Enable incremental builds for node{6,8,10}

* test: add incremental build test case

* test: add missing incremental app

* test: do not run a new shell for check_result in incremental test

* test: slightly different check for nodejs6

* check return value of s2i incremental builds as well

* Rebase to latest commons for incremental build feature

diff --git a/test/run b/test/run
--- a/test/run
+++ b/test/run
@@ -250,6 +250,28 @@ test_dev_mode() {
   kill_test_application
 }
 
+test_incremental_build() {
+  build_log1=$(ct_s2i_build_as_df file://${test_dir}/test-incremental ${IMAGE_NAME} ${IMAGE_NAME}-testapp ${s2i_args})
+  check_result $?
+  build_log2=$(ct_s2i_build_as_df file://${test_dir}/test-incremental ${IMAGE_NAME} ${IMAGE_NAME}-testapp ${s2i_args} --incremental)
+  check_result $?
+  if [ "$VERSION" == "6" ]; then
+      # Different npm output for version 6
+      if echo "$build_log2" | grep -e "\-\- yarn@[0-9\.]*"; then
+          echo "ERROR Incremental build failed: yarn package is getting installed in incremental build"
+          check_result 1
+      fi
+  else
+      first=$(echo "$build_log1" | grep -o -e "added [0-9]* packages" | awk '{ print $2 }')
+      second=$(echo "$build_log2" | grep -o -e "added [0-9]* packages" | awk '{ print $2 }')
+      if [ "$first" == "$second" ]; then
+          echo "ERROR Incremental build failed: both builds installed $first packages"
+          check_result 1
+      fi
+  fi
+
+}
+
 # Build the application image twice to ensure the 'save-artifacts' and
 # 'restore-artifacts' scripts are working properly
 prepare app
@@ -361,6 +383,9 @@ kill_test_application
 echo "Testing npm availability"
 ct_npm_works
 check_result $?
+
+echo "Testing incremental build"
+test_incremental_build
 
 echo "Success!"
 cleanup
