Be more clever about guessing FULL_IMAGE name

diff --git a/test/run-minimal b/test/run-minimal
--- a/test/run-minimal
+++ b/test/run-minimal
@@ -90,7 +90,23 @@ cid_file=$CID_FILE_DIR/$(mktemp -u -p . --suffix=.cid)
 prepare app
 check_prep_result $? app || exit
 echo "Testing the production image build"
-FULL_IMAGE=${FULL_IMAGE:-registry.access.redhat.com/ubi8/nodejs-${VERSION//-minimal/}:latest}
+
+FULL_IMAGE=${FULL_IMAGE:-${IMAGE_NAME//-minimal:1/}}
+# if FULL_IMAGE is not found, try to pull it, if that does not work, try to pull ubi9 one
+if [ -z "$(docker images -q "$FULL_IMAGE")" ] ; then
+  echo "Image $FULL_IMAGE not found, trying to pull $FULL_IMAGE from registry"
+  docker pull "$FULL_IMAGE"
+fi
+if [ -z "$(docker images -q "$FULL_IMAGE")" ] ; then
+  echo "Image $FULL_IMAGE still not found, trying to use ubi9/nodejs-${VERSION//-minimal/}:latest and pull it"
+  FULL_IMAGE="ubi9/nodejs-${VERSION//-minimal/}:latest"
+  docker pull "$FULL_IMAGE"
+fi
+if [ -z "$(docker images -q "$FULL_IMAGE")" ] ; then
+  echo "Image $FULL_IMAGE could not be found nor pulled, giving up."
+  exit 1
+fi
+
 prepare_minimal_build testapp
 
 TEST_SET=${TESTS:-$TEST_LIST_APP} ct_run_tests_from_testset "app"
